// 語系
const LANG = {
  zh: {
    alertNoData: "查無資料",
    viewAll: "查看全部",
    prevPage: "上一頁",
    nextPage: "下一頁",
    page: "第",
    total: "頁 / 共",
    sitStand: "坐站平均秒數",
    balanceScore: "平衡分數",
    gaitSpeed: "步行速度",
    fallRisk: "跌倒風險 (%)",
    countWarning: "尚無資料",
    noRecord: "尚無檢測紀錄",
    noMatchedPerson: "目前沒有符合條件的人員",
    startDateText: "自 {yearMonth} ",
    latestDateText: "{date} 檢測",
    generatingPDF: "產生中...",
    downloadPDF: "下載",
    male: "男",
    female: "女",
    yearsOld: "歲",
    people: "人",
    seconds: "秒",
    points: "分",
    gaitSpeed: "cm/s",
    fallRisk: "％",
    walkDecline: "步行速度衰退",
    sitStandIncrease: "起坐秒數增加",
    vivifrailA: "A級失能者",
    vivifrailB: "B級衰弱者",
    vivifrailC: "C級衰弱前期者",
    overview: "總表",
    riskLabel: {
      high: "危險",
      slightlyHigh: "高",
      medium: "中",
      slightlyLow: "稍低",
      low: "低",
      unknown: "未知",
    },
    vivifrailLevelLabel: {
      A: "A級",
      B: "B級",
      C: "C級",
      D: "D級",
    },

    name: "姓名",
    genderLabel: "性別",
    ageLabel: "年齡",
    riskLevel: "等級",
    dates: "日期",
    degenerateWarning: "功能衰退警示 (較前次檢測衰退超過10%)",
    highRiskGroup: "高風險族群",
    all: "全部",
    month: "月",
    noDataThisMonth: "本月無資料",
    levelOverviewText:
      "顯示每位受測者的最新測驗結果，共 {people} 位受測者（{records} 筆測驗資料）。",
    levelSingleText: "{levelName}：共 {people} 位受測者（{records} 筆資料）。",
    overviewAllText:
      "顯示每位受測者的最新測驗結果，共 {people} 位受測者（{records} 筆測驗資料）。",
    overviewLevelText: "{level}：共 {people} 位受測者（{records} 筆資料）。",
    userCount: "用戶數",
    locations: {
      taipower: "台電據點",
      ntu: "台大據點",
      dapinlin: "大坪林據點",
      zhangxin: "樟新據點",
    },
  },

  en: {
    alertNoData: "No data",
    viewAll: "View all",
    prevPage: "Previous",
    nextPage: "Next",
    page: "Page",
    total: "of",
    sitStand: "Sit-Stand Avg (s)",
    balanceScore: "Balance Score",
    gaitSpeed: "Gait Speed",
    fallRisk: "Fall Risk (%)",
    countWarning: "No data",
    noRecord: "No test records",
    noMatchedPerson: "No matching participants found",
    startDateText: "Accumulated since {yearMonth}",
    latestDateText: "Measured on {date}",
    generatingPDF: "Generating...",
    downloadPDF: "Download",
    male: "Male",
    female: "Female",
    yearsOld: "years old",
    people: "people",
    seconds: "s",
    points: "pts",
    gaitSpeed: "cm/s",
    fallRisk: "％",
    walkDecline: "Gait speed decline",
    sitStandIncrease: "Sit-stand time increase",
    vivifrailA: "Level A disabled",
    vivifrailB: "Level B frail",
    vivifrailC: "Level C pre-frail",
    overview: "Overview",
    riskLabel: {
      high: "Danger",
      slightlyHigh: "high",
      medium: "middle",
      slightlyLow: "Slightly lower",
      low: "Low",
      unknown: "Unknown",
    },
    vivifrailLevelLabel: {
      A: "A",
      B: "B",
      C: "C",
      D: "D",
    },

    name: "Name",
    genderLabel: "Gender",
    ageLabel: "Age",
    riskLevel: "Level",
    dates: "Date",
    degenerateWarning: "Degeneration Warning (decline > 10% since last test)",
    highRiskGroup: "High-Risk Group",
    all: "All",
    month: "Month",
    noDataThisMonth: "No data this month",
    levelOverviewText:
      "Showing the latest test results of each participant, total {people} participants ({records} test records).",
    levelSingleText: "{levelName}: {people} participants ({records} records).",
    overviewAllText:
      "Showing the latest result of each participant. Total {people} participants ({records} test records).",
    overviewLevelText: "{level}: {people} participants ({records} records).",
    userCount: "User Count",
    locations: {
      taipower: "Taipower Site",
      ntu: "NTU Site",
      dapinlin: "Dapinglin Site",
      zhangxin: "Zhangxin Site",
    },
  },
  ja: {
    alertNoData: "データなし",
    viewAll: "すべて表示",
    prevPage: "前ページ",
    nextPage: "次ページ",
    page: "第",
    total: "ページ / 全",
    sitStand: "座立平均秒数",
    balanceScore: "バランススコア",
    gaitSpeed: "歩行速度",
    fallRisk: "転倒リスク (%)",
    countWarning: "データなし",
    noRecord: "検査記録なし",
    noMatchedPerson: "条件に一致する参加者がいません",
    startDateText: "以来{yearMonth}",
    latestDateText: "{date} 測定",
    generatingPDF: "生成中...",
    downloadPDF: "ダウンロード",
    male: "男性",
    female: "女性",
    yearsOld: "歳",
    people: "人",
    seconds: "秒",
    points: "点",
    gaitSpeed: "cm/s",
    fallRisk: "％",
    walkDecline: "歩行速度の低下",
    sitStandIncrease: "起立時間の増加",
    vivifrailA: "A級失能者",
    vivifrailB: "B級衰弱者",
    vivifrailC: "C級衰弱前期者",
    overview: "総表",
    riskLabel: {
      high: "危険",
      slightlyHigh: "高い",
      medium: "真ん中",
      slightlyLow: "わずかに低い",
      low: "低い",
      unknown: "不明",
    },
    vivifrailLevelLabel: {
      A: "A級",
      B: "B級",
      C: "C級",
      D: "D級",
    },

    name: "名前",
    genderLabel: "性別",
    ageLabel: "年齢",
    riskLevel: "等級",
    dates: "日付",
    degenerateWarning: "機能衰退警告（前回検査より10％以上低下）",
    highRiskGroup: "高リスク群",
    all: "すべて",
    month: "月",
    noDataThisMonth: "今月データなし",
    levelOverviewText:
      "各参加者の最新検査結果を表示しています。全 {people} 名（{records} 件の検査データ）。",
    levelSingleText: "{levelName}：全 {people} 名（{records} 件のデータ）。",
    overviewAllText:
      "各受検者の最新結果を表示しています。合計 {people} 人（{records} 件の検査データ）。",
    overviewLevelText: "{level}：合計 {people} 人（{records} 件）。",
    userCount: "ユーザー数",
    locations: {
      taipower: "台電拠点",
      ntu: "台大拠点",
      dapinlin: "大坪林拠点",
      zhangxin: "樟新拠点",
    },
  },
  ko: {
    alertNoData: "데이터 없음",
    viewAll: "모두보기",
    prevPage: "이전",
    nextPage: "다음",
    page: "페이지",
    total: " / 총",
    sitStand: "좌/서 평균 초",
    balanceScore: "균형 점수",
    gaitSpeed: "보행 속도",
    fallRisk: "낙상 위험 (%)",
    countWarning: "데이터 없음",
    noRecord: "검사 기록 없음",
    noMatchedPerson: "조건에 맞는 인원이 없습니다",
    startDateText: "이래{yearMonth}",
    latestDateText: "{date} 측정",
    generatingPDF: "생성 중...",
    downloadPDF: "다운로드",
    male: "남성",
    female: "여성",
    yearsOld: "세",
    people: "명",
    seconds: "초",
    points: "점",
    gaitSpeed: "cm/s",
    fallRisk: "％",
    walkDecline: "보행 속도 감소",
    sitStandIncrease: "기립 시간 증가",
    vivifrailA: "A등급 장애자",
    vivifrailB: "B등급 허약자",
    vivifrailC: "C등급 허약 전기자",
    overview: "전체표",
    riskLabel: {
      high: "위험",
      slightlyHigh: "높은",
      medium: "가운데",
      slightlyLow: "약간 낮음",
      low: "낮은",
      unknown: "알 수 없음",
    },
    vivifrailLevelLabel: {
      A: "A등급",
      B: "B등급",
      C: "C등급",
      D: "D등급",
    },

    name: "이름",
    genderLabel: "성별",
    ageLabel: "나이",
    riskLevel: "등급",
    dates: "날짜",
    degenerateWarning: "기능 저하 경고 (이전 검사 대비 10% 이상 감소)",
    highRiskGroup: "고위험군",
    all: "전체",
    month: "월",
    noDataThisMonth: "이번 달 데이터 없음",
    levelOverviewText:
      "각 참가자의 최신 검사 결과를 보여줍니다. 총 {people} 명 ({records} 건의 검사 데이터).",
    levelSingleText: "{levelName}: 총 {people} 명 ({records} 건의 데이터).",
    overviewAllText:
      "각 참가자의 최신 검사 결과를 표시합니다. 총 {people}명 ({records}건의 검사 기록).",
    overviewLevelText: "{level}: 총 {people}명 ({records}건).",
    userCount: "사용자 수",
    locations: {
      taipower: "타이파워 거점",
      ntu: "타이완대 거점",
      dapinlin: "다핑린 거점",
      zhangxin: "장신 거점",
    },
  },
};

function t(key) {
  return LANG[window.currentLang][key] || key;
}
function tLocation(key) {
  return LANG[window.currentLang]?.locations?.[key] || key;
}
